"""add_currencies_statistics

Revision ID: 96d6f83a8448
Revises:
Create Date: 2025-05-09 13:50:26.821906

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "96d6f83a8448"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "currencies_statistics",
        sa.Column("id", sa.Integer(), nullable=False, autoincrement=True),
        sa.Column("symbol", sa.String(length=10), nullable=False),
        sa.Column("current_price", sa.Float(), nullable=False),
        sa.Column("change_24h", sa.Float(), nullable=False),
        sa.Column("volatility_percent", sa.Float(), nullable=False),
        sa.Column("volume_usd", sa.Float(), nullable=False),
        sa.Column("trades_count", sa.BigInteger(), nullable=False),
        sa.Column("relative_change", sa.Float(), nullable=False),
        sa.Column("volume_ratio", sa.Float(), nullable=False),
        sa.Column("volatility_ratio", sa.Float(), nullable=False),
        sa.Column("trades_ratio", sa.Float(), nullable=False),
        sa.Column("momentum_score", sa.Float(), nullable=False),
        sa.Column("avg_trade_size_usd", sa.Float(), nullable=False),
        sa.Column("intraday_change", sa.Float(), nullable=False),
        sa.Column("distance_from_high", sa.Float(), nullable=False),
        sa.Column("distance_from_low", sa.Float(), nullable=False),
        sa.Column("deviation_from_avg", sa.Float(), nullable=False),
        sa.Column("daily_range_percent", sa.Float(), nullable=False),
        sa.Column("market_state", sa.String(), nullable=False),
        sa.Column("action_suggestion", sa.String(), nullable=False),
        sa.Column("raw_processing_time", sa.DateTime(), nullable=False),
        sa.Column(
            "processing_time",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "valid_from", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "valid_to",
            sa.DateTime(),
            server_default=sa.text("'2999-12-31 00:00:00'::timestamp"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("currencies_statistics")
    # ### end Alembic commands ###
